"use client";
import {Children,cloneElement,isValidElement,useId,useMemo,useState,type ReactNode} from 'react';
import {CalendarDays,ChevronLeft,ChevronRight,ClipboardCheck,ExternalLink,List,Plus,RefreshCw,Search,Settings2,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import type {Benefit,Organization,Payment} from '@/lib/types';
import {newEvent,type ConferenceWatch,type Discovery,type EventDecision,type EventRecord,type PlanningData,type PlanningSnapshot} from '@/lib/planning-types';
import {addDays,dateRange,formatDate,isCritical,localToday,monthDays,moveMonth,overlapsDates,validDate} from '@/lib/event-dates';
import {matchesState,organizationStateLabel,stateOptions} from '@/lib/states';
import './events.css';

type Props={organizations:Organization[];benefits:Benefit[];payments:Payment[];snapshot:PlanningSnapshot|null;error:string;onSave:(data:PlanningData,expectedRevision:number)=>Promise<void>;onReload:()=>Promise<void>;canEdit:boolean};
type Captured={data:PlanningData;revision:number};
type EventEditor=Captured&{event:EventRecord;existing:boolean};
type WatchEditor=Captured&{watch:ConferenceWatch;existing:boolean};
const decisions:{value:EventDecision;label:string}[]=[{value:'needs_review',label:'Needs review'},{value:'attend',label:'Attend'},{value:'sponsor',label:'Sponsor'},{value:'attend_and_sponsor',label:'Attend & sponsor'},{value:'decline',label:'Do not attend / sponsor'}];
const participating=(event:EventRecord)=>event.decision!=='needs_review'&&event.decision!=='decline';
const decisionLabel=(value:EventDecision)=>decisions.find(item=>item.value===value)?.label??value;
const currency=(value:number|null)=>value===null?'Not set':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:value%100===0?0:2}).format(value/100);
const safeUrl=(value:string)=>{try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)&&!url.username&&!url.password&&!/[\s\\]/.test(value)?url.href:''}catch{return ''}};
const message=(error:unknown)=>error instanceof Error?error.message:'The change could not be saved. Please try again.';
const stamp=(value:string)=>value?new Date(value).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Not yet';
const capture=(snapshot:PlanningSnapshot):Captured=>({data:structuredClone(snapshot.data),revision:snapshot.revision});
function Field({label,children,hint,className=''}:{label:string;children:ReactNode;hint?:string;className?:string}){
 const id=useId();
 const connect=(child:ReactNode):ReactNode=>{
  if(!isValidElement<{children?:ReactNode;id?:string;'aria-labelledby'?:string;'aria-describedby'?:string}>(child))return child;
  if(typeof child.type==='string'&&['input','select','textarea'].includes(child.type))return cloneElement(child,{id,'aria-labelledby':id+'-label','aria-describedby':hint?id+'-hint':undefined});
  return child.props.children?cloneElement(child,{children:Children.map(child.props.children,connect)}):child;
 };
 return <div className={'event-field '+className}><label id={id+'-label'} htmlFor={id}>{label}</label>{Children.map(children,connect)}{hint&&<small id={id+'-hint'}>{hint}</small>}</div>;
}
function SelectField({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:{value:string;label:string}[]}){return <Field label={label}><select value={value} onChange={event=>onChange(event.target.value)}>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></Field>}
function SourceLink({url,label='Organizer source'}:{url:string;label?:string}){const href=safeUrl(url);return href?<a className="event-source" href={href} target="_blank" rel="noopener noreferrer">{label}<ExternalLink size={13}/></a>:null}
function DecisionBadge({decision}:{decision:EventDecision}){return <span className={'event-badge decision-'+decision}>{decisionLabel(decision)}</span>}

export function EventsWorkspace({organizations,benefits,payments,snapshot,error,onSave,onReload,canEdit}:Props){
 const [view,setView]=useState('schedule'),[layout,setLayout]=useState('list'),[query,setQuery]=useState(''),[sector,setSector]=useState('all'),[state,setState]=useState('all'),[organization,setOrganization]=useState('all'),[decision,setDecision]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[focus,setFocus]=useState('all');
 const [month,setMonth]=useState(localToday().slice(0,7)),[eventEditor,setEventEditor]=useState<EventEditor|null>(null),[watchEditor,setWatchEditor]=useState<WatchEditor|null>(null),[actionError,setActionError]=useState(''),[busy,setBusy]=useState(false),[archive,setArchive]=useState(false),[suggestionsLimit,setSuggestionsLimit]=useState(12);
 const today=localToday(),orgMap=useMemo(()=>new Map(organizations.map(org=>[org.id,org])),[organizations]);
 const data=snapshot?.data;
 const candidates=useMemo(()=>watchSuggestions(organizations,benefits,payments,data?.watches??[]),[organizations,benefits,payments,data?.watches]);
 const events=data?.events??[];
 const enabledWatches=data?.watches.filter(watch=>watch.enabled).length??0;
 const latestRun=data?.runs.slice().sort((a,b)=>b.startedAt.localeCompare(a.startedAt))[0];
 const schedulerOverdue=!!(data?.settings.enabled&&enabledWatches&&data.settings.nextRunAt&&Date.now()-new Date(data.settings.nextRunAt).getTime()>86_400_000);
 const trackerStatus=!data?.settings.enabled?'Paused':!enabledWatches?'Choose a conference to track':!latestRun?'Awaiting first run':schedulerOverdue?'Scheduled check is overdue':latestRun.status==='failed'?'Last check needs attention':latestRun.status==='partial'?'Some sources need attention':'Last check completed';
 const sectors=Array.from(new Set([...organizations.map(org=>org.sector),...events.map(event=>event.sector)].filter(Boolean))).sort();
 const states=stateOptions([...organizations.map(org=>org.state),...events.map(event=>event.state)]);
 const dateError=from&&to&&from>to?'The end of the date range must be on or after the start.':'';
 const scoped=events.filter(event=>(sector==='all'||event.sector===sector)&&matchesState(event.state,state)&&(organization==='all'||event.organizationId===organization)&&(decision==='all'||event.decision===decision)&&[event.title,orgMap.get(event.organizationId)?.name,event.location,event.description].join(' ').toLowerCase().includes(query.trim().toLowerCase())&&overlapsDates(event,from,to));
 const critical=scoped.filter(event=>isCritical(event,today));
 const filtered=scoped.filter(event=>focus==='critical'?isCritical(event,today):focus==='needs_review'?event.decision==='needs_review':focus==='debrief'?!!event.startDate&&(event.endDate||event.startDate)<today&&participating(event)&&!event.debrief.completedOn:focus==='undated'?!event.startDate:true).sort((a,b)=>(a.startDate||'9999').localeCompare(b.startDate||'9999')||a.title.localeCompare(b.title));
 const dated=filtered.filter(event=>validDate(event.startDate)),undated=filtered.filter(event=>!validDate(event.startDate));
 const pending=data?.discoveries.filter(discovery=>discovery.status==='new')??[];
 const openEvent=(event?:EventRecord)=>{if(!snapshot)return;setEventEditor({...capture(snapshot),event:structuredClone(event??newEvent()),existing:!!event})};
 const reviewDiscovery=(discovery:Discovery)=>{if(!snapshot)return;const org=orgMap.get(discovery.organizationId),event=newEvent(discovery.organizationId,org?.sector||'K-12');Object.assign(event,{title:discovery.title,startDate:discovery.startDate,endDate:discovery.endDate,location:discovery.location,state:discovery.state||org?.state||'',website:discovery.url,description:[discovery.summary,discovery.sponsorshipDetails].filter(Boolean).join('\n\n'),sourceDiscoveryId:discovery.id});setEventEditor({...capture(snapshot),event,existing:false})};
 const mutate=async(change:(draft:PlanningData)=>void)=>{if(!snapshot||!canEdit)return;const base=capture(snapshot);change(base.data);setBusy(true);setActionError('');try{await onSave(base.data,base.revision)}catch(error){setActionError(message(error))}finally{setBusy(false)}};
 const reload=async()=>{setActionError('');setBusy(true);try{await onReload()}catch(error){setActionError(message(error))}finally{setBusy(false)}};
 const openWatch=(watch?:ConferenceWatch)=>{if(snapshot)setWatchEditor({...capture(snapshot),watch:structuredClone(watch??{id:'watch-'+crypto.randomUUID(),organizationId:'',name:'',sourceUrls:[],searchTerms:'',enabled:true}),existing:!!watch})};
 return <section className="events-workspace" aria-label="Events overview">
  <div className="events-heading"><div><p className="eyebrow">CORE MIDWEST / EVENTS & CONFERENCES</p><h2>Plan the next opportunity.</h2><p>Find conferences, decide how to participate, and keep your team ready.</p></div><div className="events-actions"><Button variant="outline" onClick={reload} disabled={busy}><RefreshCw size={15}/>Refresh events</Button><Button onClick={()=>openEvent()} disabled={!snapshot||!canEdit}><Plus size={16}/>Add event</Button></div></div>
  {(error||actionError)&&<div className="event-alert" role="alert">{actionError||error}</div>}
  {!snapshot?<div className="event-empty event-setup"><CalendarDays size={30}/><h3>Events are not connected yet.</h3><p>Your organization spending is still available. The shared events setup needs to be completed before plans or conference searches can be saved.</p><Button variant="outline" onClick={reload} disabled={busy}>Check connection</Button></div>:<>
   <Tabs value={view} onValueChange={setView}><TabsList variant="line" className="events-nav"><TabsTrigger value="schedule"><CalendarDays size={16}/>Overview</TabsTrigger><TabsTrigger value="review"><ClipboardCheck size={16}/>Discovery review <span className="count">{pending.length}</span></TabsTrigger><TabsTrigger value="tracking"><Settings2 size={16}/>Conference tracking</TabsTrigger></TabsList>
    <TabsContent value="schedule">
     <div className="event-metrics"><button onClick={()=>setFocus(focus==='critical'?'all':'critical')} aria-pressed={focus==='critical'} className="event-metric critical-metric"><span>Critical · next 4 weeks</span><strong>{critical.length}</strong><small>{formatDate(today,{month:'short',day:'numeric'})} – {formatDate(addDays(today,27),{month:'short',day:'numeric'})} · includes ongoing events</small></button><button onClick={()=>setFocus(focus==='needs_review'?'all':'needs_review')} aria-pressed={focus==='needs_review'} className="event-metric"><span>Participation decisions</span><strong>{scoped.filter(event=>event.decision==='needs_review').length}</strong><small>Waiting for your review</small></button><button onClick={()=>setFocus(focus==='undated'?'all':'undated')} aria-pressed={focus==='undated'} className="event-metric"><span>Needs a date</span><strong>{scoped.filter(event=>!event.startDate).length}</strong><small>Confirm dates to place on the calendar</small></button><button onClick={()=>setFocus(focus==='debrief'?'all':'debrief')} aria-pressed={focus==='debrief'} className="event-metric"><span>Debriefs to complete</span><strong>{scoped.filter(event=>!!event.startDate&&(event.endDate||event.startDate)<today&&participating(event)&&!event.debrief.completedOn).length}</strong><small>Capture results and next steps</small></button></div>
     <div className="event-filters"><Field label="Find an event" className="event-search"><div><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Event, organization, or place"/></div></Field><SelectField label="Event market" value={sector} onChange={setSector} options={[{value:'all',label:'All markets'},...sectors.map(value=>({value,label:value}))]}/><SelectField label="Event state" value={state} onChange={setState} options={states}/><SelectField label="Event organization" value={organization} onChange={setOrganization} options={[{value:'all',label:'All organizations'},...organizations.map(org=>({value:org.id,label:org.name})).sort((a,b)=>a.label.localeCompare(b.label))]}/><SelectField label="Participation" value={decision} onChange={setDecision} options={[{value:'all',label:'All decisions'},...decisions]}/><Field label="From date"><input type="date" max="2200-12-31" value={from} onChange={event=>setFrom(event.target.value)}/></Field><Field label="Through date"><input type="date" max="2200-12-31" value={to} onChange={event=>setTo(event.target.value)}/></Field></div>
     {dateError&&<p className="form-error" role="alert">{dateError}</p>}
     <div className="event-list-toolbar"><div><strong>{filtered.length} {filtered.length===1?'event':'events'}</strong>{focus!=='all'&&<button className="event-text-button" onClick={()=>setFocus('all')}>Clear selected summary</button>}<span className="event-caption">Totals follow the filters above.</span></div><div className="event-layout" aria-label="Event layout"><Button variant={layout==='list'?'default':'outline'} aria-pressed={layout==='list'} onClick={()=>setLayout('list')}><List size={15}/>List</Button><Button variant={layout==='calendar'?'default':'outline'} aria-pressed={layout==='calendar'} onClick={()=>setLayout('calendar')}><CalendarDays size={15}/>Calendar</Button></div></div>
     {layout==='calendar'?<EventCalendar events={dated} month={month} onMonth={setMonth} today={today} onOpen={openEvent}/>:<div className="event-list">{dated.map(event=><EventCard key={event.id} event={event} organization={orgMap.get(event.organizationId)} today={today} onOpen={()=>openEvent(event)}/>)}</div>}
     {undated.length>0&&<div className="event-undated"><h3>Needs a date <span className="count">{undated.length}</span></h3><p>These events stay off the calendar until dates are confirmed.</p><div className="event-list">{undated.map(event=><EventCard key={event.id} event={event} organization={orgMap.get(event.organizationId)} today={today} onOpen={()=>openEvent(event)}/>)}</div></div>}
     {!filtered.length&&<div className="event-empty"><CalendarDays size={30}/><h3>{events.length?'No events match these filters.':'Your event schedule starts here.'}</h3><p>{events.length?'Try another date range or clear the selected summary.':'Add an event or enable a known conference in Conference tracking. Discovered dates stay in review until you accept them.'}</p>{!events.length&&canEdit&&<Button onClick={()=>openEvent()}><Plus size={16}/>Add your first event</Button>}</div>}
     <p className="event-footnote">Critical means an event overlaps today through the next 27 days. Declined events are excluded. Invoice confirmations are entered by your team and do not change the spending ledger.</p>
    </TabsContent>
    <TabsContent value="review"><div className="event-section-heading"><div><h3>Conference discoveries</h3><p>Check the organizer’s source, confirm the date and cost, then decide whether CORE Midwest will attend or sponsor.</p></div><label className="event-check"><input type="checkbox" checked={archive} onChange={event=>setArchive(event.target.checked)}/>Show reviewed results</label></div><div className="discovery-list">{data?.discoveries.filter(discovery=>archive||discovery.status==='new').map(discovery=><article key={discovery.id} className="discovery-card"><div className="discovery-top"><div><p className="eyebrow">{orgMap.get(discovery.organizationId)?.name||'Organization not assigned'}</p><h3>{discovery.title}</h3><p className="event-caption">{dateRange(discovery.startDate,discovery.endDate)}{discovery.location?' · '+discovery.location:''}</p></div><span className={'event-badge discovery-'+discovery.status}>{discovery.status==='new'?'Needs source review':discovery.status==='accepted'?'Added to events':'Dismissed'}</span></div><p>{discovery.summary}</p>{discovery.sponsorshipDetails&&<div className="discovery-benefits"><strong>Sponsorship details found</strong><p>{discovery.sponsorshipDetails}</p></div>}<div className="event-card-bottom"><SourceLink url={discovery.url}/><span className="event-caption">Found {stamp(discovery.firstSeenAt)}</span></div>{discovery.evidence.length>0&&<details className="discovery-evidence"><summary>View source excerpts</summary>{discovery.evidence.map((evidence,index)=><div key={index}><blockquote>{evidence.excerpt}</blockquote><SourceLink url={evidence.url} label="Open source"/></div>)}</details>}<div className="discovery-actions">{discovery.status==='new'?<><Button variant="outline" disabled={!canEdit||busy} onClick={()=>mutate(draft=>{const item=draft.discoveries.find(item=>item.id===discovery.id);if(item)item.status='dismissed'})}>Dismiss</Button><Button disabled={!canEdit} onClick={()=>reviewDiscovery(discovery)}>Review & add event</Button></>:discovery.status==='accepted'?<Button variant="outline" disabled={!events.some(event=>event.id===discovery.eventId)} onClick={()=>openEvent(events.find(event=>event.id===discovery.eventId))}>View event</Button>:<Button variant="outline" disabled={!canEdit||busy} onClick={()=>mutate(draft=>{const item=draft.discoveries.find(item=>item.id===discovery.id);if(item)item.status='new'})}>Return to review</Button>}</div></article>)}</div>{!(data?.discoveries.filter(discovery=>archive||discovery.status==='new').length)&&<div className="event-empty"><ClipboardCheck size={30}/><h3>No discoveries waiting for review.</h3><p>Enable conference tracking to check known organizer pages every two weeks. Results will appear here with their sources.</p><Button variant="outline" onClick={()=>setView('tracking')}>Open conference tracking</Button></div>}</TabsContent>
    <TabsContent value="tracking"><div className="tracking-status"><div><p className="eyebrow">EVERY TWO WEEKS</p><h3>Keep known conferences in view.</h3><p>Enable the conferences your team wants to follow. New information comes back for review before an event is added or participation is approved.</p></div><label className="event-switch"><input type="checkbox" checked={data?.settings.enabled??false} disabled={!canEdit||busy} onChange={event=>{const enabled=event.target.checked;void mutate(draft=>{draft.settings={...draft.settings,enabled,intervalDays:14}})}}/><span>{data?.settings.enabled?'Schedule enabled':'Schedule paused'}</span></label><p className="tracking-health" role="status"><strong>{trackerStatus}</strong>{schedulerOverdue&&<> · <a href="https://github.com/BriceCORE/Events-Sponsorships/actions/workflows/discovery.yml" target="_blank" rel="noopener noreferrer">Check the search schedule</a></>}</p><div className="tracking-dates"><span><strong>Last check</strong>{stamp(data?.settings.lastRunAt??'')}</span><span><strong>Next check due</strong>{data?.settings.enabled?data.settings.nextRunAt?stamp(data.settings.nextRunAt):'Awaiting scheduler setup':'Paused'}</span><span><strong>Enabled conferences</strong>{data?.watches.filter(watch=>watch.enabled).length??0}</span></div></div><div className="event-section-heading"><div><h3>Tracked conferences</h3><p>Use official conference or organization event pages as sources.</p></div><Button variant="outline" disabled={!canEdit} onClick={()=>openWatch()}><Plus size={15}/>Track a conference</Button></div><div className="watch-list">{data?.watches.map(watch=><article key={watch.id} className="watch-card"><div><p className="eyebrow">{orgMap.get(watch.organizationId)?.name||'Organization not assigned'}</p><h3>{watch.name}</h3><div className="watch-sources">{watch.sourceUrls.map((url,index)=><SourceLink key={url} url={url} label={'Source '+(index+1)}/>)}</div>{watch.searchTerms&&<p className="event-caption">Search terms: {watch.searchTerms}</p>}</div><div className="watch-controls"><span className={'event-badge '+(watch.enabled?'decision-attend':'')}>{watch.enabled?'Enabled':'Paused'}</span><Button variant="outline" onClick={()=>openWatch(watch)}>{canEdit?'Edit tracking':'View tracking'}</Button></div></article>)}</div>{!data?.watches.length&&<div className="event-inline-empty">No conferences are being tracked yet. Add one or start from the historical suggestions below.</div>}
     {candidates.length>0&&<section className="watch-suggestions"><div className="event-section-heading"><div><h3>Suggested from your existing records</h3><p>These names appear in benefit research or spending descriptions. They are historical clues; they do not confirm attendance or future dates.</p></div><span className="count">{candidates.length} suggestions</span></div><div className="suggestion-grid">{candidates.slice(0,suggestionsLimit).map(candidate=><article className="suggestion-card" key={candidate.organizationId+'-'+candidate.name}><p className="eyebrow">{orgMap.get(candidate.organizationId)?.name}</p><h4>{candidate.name}</h4><p>{candidate.evidence}</p><Button variant="outline" disabled={!canEdit} onClick={()=>openWatch({id:'watch-'+crypto.randomUUID(),organizationId:candidate.organizationId,name:candidate.name,sourceUrls:candidate.sourceUrls,searchTerms:candidate.name,enabled:true})}>Review tracking setup</Button></article>)}</div>{candidates.length>suggestionsLimit&&<Button variant="ghost" onClick={()=>setSuggestionsLimit(limit=>limit+12)}>Show more suggestions</Button>}</section>}
     <section className="tracking-history"><h3>Search history</h3>{data?.runs.length?<div className="run-list">{[...data.runs].sort((a,b)=>b.startedAt.localeCompare(a.startedAt)).slice(0,10).map(run=><div className="run-card" key={run.id}><div><strong>{run.status==='success'?'Check complete':run.status==='partial'?'Some sources need attention':'Check could not finish'}</strong><p>{run.message}</p></div><span>{stamp(run.startedAt)}<small>{run.pagesChecked} pages · {run.candidatesFound} discoveries</small></span></div>)}</div>:<p className="event-caption">No completed searches yet. The schedule checks enabled conference sources every 14 days.</p>}</section>
    </TabsContent>
   </Tabs>
  </>}
  {eventEditor&&<EventDialog key={eventEditor.event.id} editor={eventEditor} organizations={organizations} canEdit={canEdit} onClose={()=>setEventEditor(null)} onSave={onSave}/>}
  {watchEditor&&<WatchDialog key={watchEditor.watch.id} editor={watchEditor} organizations={organizations} canEdit={canEdit} onClose={()=>setWatchEditor(null)} onSave={onSave}/>}
 </section>;
}

function EventCard({event,organization,today,onOpen}:{event:EventRecord;organization?:Organization;today:string;onOpen:()=>void}){
 const critical=isCritical(event,today),overdue=event.tasks.filter(task=>!task.done&&task.dueDate&&task.dueDate<today).length,completed=event.tasks.filter(task=>task.done).length;
 return <article className={'event-card '+(critical?'event-card-critical':'')}><div className="event-date-tile">{event.startDate?<><span>{formatDate(event.startDate,{month:'short'})}</span><strong>{formatDate(event.startDate,{day:'numeric'})}</strong><small>{event.startDate.slice(0,4)}</small></>:<><CalendarDays size={22}/><small>Date needed</small></>}</div><div className="event-card-content"><div className="event-card-top"><p className="eyebrow">{organization?.name||'Organization not assigned'}</p>{critical&&<span className="event-badge critical-badge">Critical · next 4 weeks</span>}</div><button className="event-title-button" onClick={onOpen}>{event.title}</button><p className="event-caption">{dateRange(event.startDate,event.endDate)}{event.location?' · '+event.location:''}{event.state?' · '+organizationStateLabel(event.state):''}</p><div className="event-card-tags"><DecisionBadge decision={event.decision}/><span className={'event-badge '+(event.invoice.status==='paid'?'invoice-paid':'')}>{event.invoice.status==='paid'?'Payment manually confirmed':event.invoice.status==='awaiting_payment'?'Invoice awaiting payment':'Invoice not received'}</span>{event.tasks.length>0&&<span className="event-caption">{completed}/{event.tasks.length} planning tasks</span>}{overdue>0&&<span className="event-badge critical-badge">{overdue} overdue {overdue===1?'task':'tasks'}</span>}{event.debrief.completedOn&&<span className="event-badge">Debrief complete</span>}</div></div><div className="event-card-end"><span>Estimated commitment<strong>{currency(event.estimatedCostCents)}</strong></span><Button variant="outline" onClick={onOpen}>Open event<ChevronRight size={15}/></Button></div></article>;
}
function EventCalendar({events,month,onMonth,today,onOpen}:{events:EventRecord[];month:string;onMonth:(month:string)=>void;today:string;onOpen:(event:EventRecord)=>void}){
 return <section className="event-calendar" aria-label="Month calendar"><div className="calendar-toolbar"><h3>{formatDate(month+'-01',{month:'long',year:'numeric'})}</h3><div><Button variant="ghost" onClick={()=>onMonth(today.slice(0,7))}>This month</Button><Button variant="outline" aria-label="Previous month" onClick={()=>onMonth(moveMonth(month,-1))}><ChevronLeft size={16}/></Button><Button variant="outline" aria-label="Next month" onClick={()=>onMonth(moveMonth(month,1))}><ChevronRight size={16}/></Button></div></div><div className="calendar-scroll"><div className="calendar-grid" role="grid" aria-label={formatDate(month+'-01',{month:'long',year:'numeric'})}>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><div className="calendar-day-name" role="columnheader" key={day}>{day}</div>)}{monthDays(month).map(day=><div key={day} role="gridcell" aria-label={formatDate(day,{weekday:'long',month:'long',day:'numeric',year:'numeric'})} className={'calendar-day '+(!day.startsWith(month)?'other-month ':'')+(day===today?'is-today':'')}><span className="calendar-number">{Number(day.slice(-2))}</span>{events.filter(event=>overlapsDates(event,day,day)).map(event=><button key={event.id} className={'calendar-event '+(isCritical(event,today)?'calendar-critical ':'')+(event.decision==='decline'?'calendar-declined':'')} title={event.title+' · '+dateRange(event.startDate,event.endDate)} onClick={()=>onOpen(event)}>{event.title}</button>)}</div>)}</div></div><p className="event-footnote">Select an event to open its plan. Events spanning several days appear on each day.</p></section>;
}

function EventDialog({editor,organizations,canEdit,onClose,onSave}:{editor:EventEditor;organizations:Organization[];canEdit:boolean;onClose:()=>void;onSave:Props['onSave']}){
 const [draft,setDraft]=useState(()=>structuredClone(editor.event)),[tab,setTab]=useState('details'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[estimate,setEstimate]=useState(editor.event.estimatedCostCents===null?'':String(editor.event.estimatedCostCents/100)),[invoiceAmount,setInvoiceAmount]=useState(editor.event.invoice.amountCents===null?'':String(editor.event.invoice.amountCents/100));
 const patch=(changes:Partial<EventRecord>)=>setDraft(value=>({...value,...changes}));
 const field=(name:keyof Pick<EventRecord,'title'|'location'|'state'|'sector'|'website'|'sponsorshipLevel'>,label:string)=> <Field label={label}><input value={draft[name]} maxLength={name==='website'?2000:500} onChange={event=>patch({[name]:event.target.value})}/></Field>;
 const moneyValue=(value:string,label:string)=>{if(!value.trim())return null;if(!/^\d+(\.\d{1,2})?$/.test(value.trim()))throw new Error(label+' must be a positive dollar amount with up to two decimal places.');const cents=Math.round(Number(value)*100);if(!Number.isSafeInteger(cents)||cents>100000000000)throw new Error(label+' is too large.');if(cents<=0)throw new Error(label+' must be greater than zero, or leave it blank.');return cents};
 const save=async()=>{setError('');try{
  if(!draft.title.trim())throw new Error('Enter an event name.');
  if(!draft.organizationId)throw new Error('Choose an organization.');
  if(!draft.sector.trim())throw new Error('Enter the event market.');
  if(draft.startDate&&!validDate(draft.startDate)||draft.endDate&&!validDate(draft.endDate))throw new Error('Enter valid event dates.');
  if(draft.endDate&&(!draft.startDate||draft.endDate<draft.startDate))throw new Error('The end date must be on or after the start date.');
  if(draft.website&&!safeUrl(draft.website))throw new Error('Use a complete organizer link starting with https:// or http://.');
  if(draft.invoice.status==='paid'&&(!draft.invoice.paidOn||!draft.invoice.confirmedBy.trim()||!draft.invoice.reference.trim()&&!draft.invoice.note.trim()))throw new Error('To confirm payment, enter the paid date, who confirmed it, and an invoice reference or confirmation note.');
  if(draft.tasks.some(task=>!task.title.trim()))throw new Error('Give each planning task a name or remove the empty task.');
  const saved={...draft,title:draft.title.trim(),estimatedCostCents:moneyValue(estimate,'Estimated cost'),invoice:{...draft.invoice,amountCents:moneyValue(invoiceAmount,'Invoice amount')},updatedAt:new Date().toISOString()};
  const data=structuredClone(editor.data);data.events=editor.existing?data.events.map(event=>event.id===draft.id?saved:event):[...data.events,saved];
  if(saved.sourceDiscoveryId){const discovery=data.discoveries.find(discovery=>discovery.id===saved.sourceDiscoveryId);if(discovery){discovery.status='accepted';discovery.eventId=saved.id}}
  setBusy(true);await onSave(data,editor.revision);onClose();
 }catch(error){setError(message(error))}finally{setBusy(false)}};
 const textArea=(label:string,value:string,onChange:(value:string)=>void,hint?:string)=><Field label={label} hint={hint}><textarea rows={3} maxLength={10000} value={value} onChange={event=>onChange(event.target.value)}/></Field>;
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent className="event-dialog" showCloseButton={!busy}><DialogHeader><DialogTitle>{editor.existing?draft.title||'Event details':'Add an event'}</DialogTitle><DialogDescription>{canEdit?'Keep the event decision, payment confirmation, plan, and debrief together.':'You can view event details. An owner or editor can make changes.'}</DialogDescription></DialogHeader><Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="event-editor-tabs"><TabsTrigger value="details">Event & decision</TabsTrigger><TabsTrigger value="invoice">Invoice</TabsTrigger><TabsTrigger value="plan">Planning</TabsTrigger><TabsTrigger value="debrief">Debrief</TabsTrigger></TabsList><fieldset disabled={!canEdit||busy} className="event-editor-fields">
 <TabsContent value="details"><div className="event-form-grid"><Field label="Event name" className="event-span-two"><input value={draft.title} maxLength={500} onChange={event=>patch({title:event.target.value})}/></Field><Field label="Organization" className="event-span-two"><select value={draft.organizationId} disabled={!!draft.sourceDiscoveryId} onChange={event=>{const org=organizations.find(org=>org.id===event.target.value),previous=organizations.find(org=>org.id===draft.organizationId);patch({organizationId:event.target.value,...(org&&(!draft.organizationId||!draft.sector||draft.sector===previous?.sector)?{sector:org.sector}:{}),...(org&&(!draft.organizationId||!draft.state||draft.state===previous?.state)?{state:org.state}:{})})}}><option value="">Choose an organization</option>{organizations.map(org=><option key={org.id} value={org.id}>{org.name}</option>)}</select></Field><Field label="Start date" hint="Leave blank until the organizer confirms."><input type="date" max="2200-12-31" value={draft.startDate} onChange={event=>patch({startDate:event.target.value})}/></Field><Field label="End date"><input type="date" max="2200-12-31" min={draft.startDate||undefined} value={draft.endDate} onChange={event=>patch({endDate:event.target.value})}/></Field>{field('location','Venue / city')}{field('state','Event state')}{field('sector','Market')}{field('website','Organizer / registration link')}<div className="event-span-two">{textArea('Event details',draft.description,value=>patch({description:value}))}</div><SelectField label="CORE Midwest decision" value={draft.decision} onChange={value=>patch({decision:value as EventDecision})} options={decisions}/>{field('sponsorshipLevel','Sponsorship level')}<Field label="Estimated cost ($)"><input inputMode="decimal" value={estimate} placeholder="Not set" onChange={event=>setEstimate(event.target.value)}/></Field><p className="event-form-note">Owners and editors can approve attendance or sponsorship. Estimates are planning amounts and do not add spending to the ledger.</p><div className="event-span-two">{textArea('Decision notes',draft.decisionNotes,value=>patch({decisionNotes:value}),'Record the reason, approval, or conditions for participation.')}</div></div></TabsContent>
 <TabsContent value="invoice"><div className="event-form-grid"><div className="event-editor-notice event-span-two">Enter a confirmation after your team verifies the invoice has been paid. This is a manual record; the app does not send payments or reconcile your accounting system.</div><SelectField label="Invoice status" value={draft.invoice.status} onChange={value=>patch({invoice:{...draft.invoice,status:value as EventRecord['invoice']['status']}})} options={[{value:'not_received',label:'Invoice not received'},{value:'awaiting_payment',label:'Awaiting payment'},{value:'paid',label:'Paid — manually confirmed'}]}/><Field label="Invoice amount ($)"><input inputMode="decimal" value={invoiceAmount} onChange={event=>setInvoiceAmount(event.target.value)} placeholder="Not recorded"/></Field><Field label="Invoice / payment reference"><input value={draft.invoice.reference} maxLength={500} onChange={event=>patch({invoice:{...draft.invoice,reference:event.target.value}})}/></Field><Field label="Paid on"><input type="date" max="2200-12-31" value={draft.invoice.paidOn} onChange={event=>patch({invoice:{...draft.invoice,paidOn:event.target.value}})}/></Field><Field label="Confirmed by" hint="Name of the team member who verified payment."><input value={draft.invoice.confirmedBy} maxLength={500} onChange={event=>patch({invoice:{...draft.invoice,confirmedBy:event.target.value}})}/></Field><div className="event-span-two">{textArea('Payment confirmation note',draft.invoice.note,value=>patch({invoice:{...draft.invoice,note:value}}),'For a paid invoice, include a reference or a note describing how payment was confirmed.')}</div></div></TabsContent>
 <TabsContent value="plan"><div className="event-form-grid">{textArea('Objectives',draft.plan.objectives,value=>patch({plan:{...draft.plan,objectives:value}}),'What would make this event worthwhile?')}{textArea('Audience / relationships',draft.plan.audience,value=>patch({plan:{...draft.plan,audience:value}}))}{textArea('CORE Midwest attendees',draft.plan.attendees,value=>patch({plan:{...draft.plan,attendees:value}}))}{textArea('Travel, registration & logistics',draft.plan.logistics,value=>patch({plan:{...draft.plan,logistics:value}}))}{textArea('Materials & sponsorship deliverables',draft.plan.materials,value=>patch({plan:{...draft.plan,materials:value}}))}{textArea('Follow-up process',draft.plan.followUp,value=>patch({plan:{...draft.plan,followUp:value}}))}</div><div className="event-task-heading"><h3>Planning checklist</h3><Button type="button" variant="outline" disabled={draft.tasks.length>=100} onClick={()=>patch({tasks:[...draft.tasks,{id:'task-'+crypto.randomUUID(),title:'',owner:'',dueDate:'',done:false}]})}><Plus size={14}/>Add task</Button></div>{!draft.tasks.length&&<p className="event-caption">Create your process with named owners and due dates.</p>}<div className="event-task-list">{draft.tasks.map((task,index)=>{const change=(changes:Partial<typeof task>)=>patch({tasks:draft.tasks.map(item=>item.id===task.id?{...item,...changes}:item)});return <div className="event-task" key={task.id}><label className="task-done"><input type="checkbox" checked={task.done} aria-label={'Complete task '+(task.title||index+1)} onChange={event=>change({done:event.target.checked})}/></label><Field label={'Task '+(index+1)}><input value={task.title} maxLength={500} onChange={event=>change({title:event.target.value})} placeholder="e.g., Confirm booth and registrations"/></Field><Field label="Owner"><input value={task.owner} maxLength={500} onChange={event=>change({owner:event.target.value})}/></Field><Field label="Due date"><input type="date" max="2200-12-31" value={task.dueDate} onChange={event=>change({dueDate:event.target.value})}/></Field><Button type="button" variant="ghost" aria-label={'Remove task '+(index+1)} onClick={()=>patch({tasks:draft.tasks.filter(item=>item.id!==task.id)})}><Trash2 size={16}/></Button></div>})}</div></TabsContent>
 <TabsContent value="debrief"><div className="event-form-grid"><Field label="Debrief completed on" hint="Leave blank while the debrief is in progress."><input type="date" max="2200-12-31" value={draft.debrief.completedOn} onChange={event=>patch({debrief:{...draft.debrief,completedOn:event.target.value}})}/></Field><p className="event-form-note">Capture observed results and follow-up actions so the next sponsorship decision has context.</p>{textArea('Attendance / audience reached',draft.debrief.attendance,value=>patch({debrief:{...draft.debrief,attendance:value}}))}{textArea('Meetings & conversations',draft.debrief.meetings,value=>patch({debrief:{...draft.debrief,meetings:value}}))}{textArea('Leads / new relationships',draft.debrief.leads,value=>patch({debrief:{...draft.debrief,leads:value}}))}{textArea('Opportunities / potential value',draft.debrief.opportunities,value=>patch({debrief:{...draft.debrief,opportunities:value}}),'Separate observed opportunities from confirmed revenue.')}{textArea('What worked',draft.debrief.whatWorked,value=>patch({debrief:{...draft.debrief,whatWorked:value}}))}{textArea('What to improve',draft.debrief.improvements,value=>patch({debrief:{...draft.debrief,improvements:value}}))}{textArea('Follow-up actions & owners',draft.debrief.followUp,value=>patch({debrief:{...draft.debrief,followUp:value}}))}{textArea('Additional notes',draft.debrief.notes,value=>patch({debrief:{...draft.debrief,notes:value}}))}</div></TabsContent>
 </fieldset></Tabs>{error&&<div className="event-alert" role="alert">{error}<p>Your draft is still here. If another person changed the workspace, copy any notes you need, close this editor, refresh events, and reopen before saving.</p></div>}<DialogFooter><Button variant="outline" onClick={onClose} disabled={busy}>{canEdit?'Cancel':'Close'}</Button>{canEdit&&<Button onClick={save} disabled={busy}>{busy?'Saving…':editor.existing?'Save event':'Save event & decision'}</Button>}</DialogFooter></DialogContent></Dialog>;
}

function WatchDialog({editor,organizations,canEdit,onClose,onSave}:{editor:WatchEditor;organizations:Organization[];canEdit:boolean;onClose:()=>void;onSave:Props['onSave']}){
 const [watch,setWatch]=useState(()=>structuredClone(editor.watch)),[urls,setUrls]=useState(editor.watch.sourceUrls.join('\n')),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const save=async()=>{setError('');try{if(!watch.name.trim()||!watch.organizationId)throw new Error('Enter a conference name and choose its organization.');const sourceUrls=[...new Set(urls.split(/\n/).map(url=>url.trim()).filter(Boolean))];if(sourceUrls.length>20)throw new Error('Use up to 20 official source pages per conference.');if(sourceUrls.some(url=>!safeUrl(url)))throw new Error('Use complete source links starting with https:// or http://, one per line.');if(watch.enabled&&!sourceUrls.length)throw new Error('Add at least one official source page before enabling this conference.');const saved={...watch,name:watch.name.trim(),sourceUrls};const data=structuredClone(editor.data);data.watches=editor.existing?data.watches.map(item=>item.id===watch.id?saved:item):[...data.watches,saved];setBusy(true);await onSave(data,editor.revision);onClose()}catch(error){setError(message(error))}finally{setBusy(false)}};
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent className="event-dialog watch-dialog" showCloseButton={!busy}><DialogHeader><DialogTitle>{editor.existing?'Conference tracking':'Track a conference'}</DialogTitle><DialogDescription>Monitor the official pages for a known conference. Results will be held for your review.</DialogDescription></DialogHeader><fieldset className="event-editor-fields event-form-grid" disabled={!canEdit||busy}><Field label="Conference name" className="event-span-two"><input maxLength={500} value={watch.name} onChange={event=>setWatch(value=>({...value,name:event.target.value}))}/></Field><Field label="Organization" className="event-span-two"><select value={watch.organizationId} onChange={event=>setWatch(value=>({...value,organizationId:event.target.value}))}><option value="">Choose an organization</option>{organizations.map(org=><option value={org.id} key={org.id}>{org.name}</option>)}</select></Field><Field label="Official source pages" className="event-span-two" hint="One complete URL per line. Start with the organizer’s annual conference or events page."><textarea rows={4} value={urls} onChange={event=>setUrls(event.target.value)} placeholder="https://organization.org/conference"/></Field><Field label="Search terms / conference keywords" className="event-span-two"><input maxLength={1000} value={watch.searchTerms} onChange={event=>setWatch(value=>({...value,searchTerms:event.target.value}))}/></Field><label className="event-check event-span-two"><input type="checkbox" checked={watch.enabled} onChange={event=>setWatch(value=>({...value,enabled:event.target.checked}))}/>Include this conference in the every-two-weeks check</label><p className="event-caption event-span-two">The global tracking switch must also be enabled. Tracking never approves attendance, sponsorship, or an invoice automatically.</p></fieldset>{error&&<div role="alert" className="event-alert">{error}</div>}<DialogFooter><Button variant="outline" disabled={busy} onClick={onClose}>{canEdit?'Cancel':'Close'}</Button>{canEdit&&<Button disabled={busy} onClick={save}>{busy?'Saving…':'Save tracking'}</Button>}</DialogFooter></DialogContent></Dialog>;
}

type WatchSuggestion={organizationId:string;name:string;sourceUrls:string[];evidence:string};
function watchSuggestions(organizations:Organization[],benefits:Benefit[],payments:Payment[],watches:ConferenceWatch[]):WatchSuggestion[]{
 const names=new Map(organizations.map(org=>[org.id,org.name])),seen=new Set(watches.map(watch=>watch.organizationId+'|'+watch.name.trim().toLowerCase())),result:WatchSuggestion[]=[];
 const eventPattern=/\b(conference|summit|convention|expo|annual meeting|symposium|forum)\b/i;
 const add=(organizationId:string,name:string,sourceUrls:string[],evidence:string)=>{const key=organizationId+'|'+name.trim().toLowerCase();if(!names.has(organizationId)||seen.has(key)||!eventPattern.test(name))return;seen.add(key);result.push({organizationId,name,sourceUrls:[...new Set(sourceUrls.filter(url=>safeUrl(url)))].slice(0,8),evidence})};
 for(const benefit of benefits)for(const organizationId of benefit.organizationIds)add(organizationId,benefit.program,benefit.sources,'From existing benefit research: '+benefit.sourceOrganization);
 for(const payment of payments){if(!eventPattern.test(payment.description))continue;for(const allocation of payment.allocations)add(allocation.organizationId,payment.description.slice(0,500),[],'From a historical spending description'+(payment.eventYear?' ('+payment.eventYear+')':'')+'. Confirm the recurring conference name and organizer page.');}
 return result;
}
