"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Building2,Search,ArrowUpRight,ReceiptText,Plus,Download,Check,ChevronRight,RefreshCw,X,ExternalLink} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from "@/components/ui/dialog";
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from "@/components/ui/table";
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from "@/components/ui/combobox";
import {Checkbox} from "@/components/ui/checkbox";
import {Toaster,toast} from "sonner";
import type {Data,Organization,Payment,Benefit} from "@/lib/types";
import {api,canEdit,localPreview} from "@/lib/shared-client";
import {CoreBrand} from "./auth-gate";
import {WorkspaceTools} from "./workspace-tools";
import {OrganizationLogo,LogoSource} from "./organization-logo";
import {matchesPeriod,unassigned} from "@/lib/review";
import {matchesState,stateLabel,stateOptions,organizationStateLabel,compareOrganizationStates} from "@/lib/states";

const money=(c:number|null)=>c===null?"Not recorded":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2,minimumFractionDigits:c%100===0?0:2}).format(c/100);
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue /></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
function downloadCsv(name:string,rows:unknown[][]){const esc=(v:unknown)=>'"'+String(v??"").replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const blob=new Blob(["\uFEFF"+rows.map(r=>r.map(esc).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8;"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}

export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState("");
 const [sector,setSector]=useState("K-12"),[year,setYear]=useState("2026"),[basis,setBasis]=useState("event");
 const [state,setState]=useState("all");
 const [view,setView]=useState("organizations"),[query,setQuery]=useState(""),[selected,setSelected]=useState("");
 const [tab,setTab]=useState("spending"),[expenseQuery,setExpenseQuery]=useState(""),[filter,setFilter]=useState("all"),[sort,setSort]=useState("spend");
 const [editing,setEditing]=useState<Payment|null>(null),[adding,setAdding]=useState(false),[benefitEdit,setBenefitEdit]=useState<Benefit|null>(null);
 const load=useCallback(async()=>{try{setError("");const d=await api("/api/workspace");setData(d);setSelected(s=>s||d.organizations.find((o:Organization)=>o.name.includes("Greater Clark"))?.id||d.organizations[0]?.id||"");}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(editing||adding||benefitEdit||localPreview)return; const refresh=()=>{if(document.visibilityState==="visible")void load()}; const timer=window.setInterval(refresh,30000);window.addEventListener("focus",refresh);return()=>{window.clearInterval(timer);window.removeEventListener("focus",refresh)}},[load,editing,adding,benefitEdit]);
 const orgMap=useMemo(()=>new Map(data?.organizations.map(o=>[o.id,o])??[]),[data]);
 const period=useMemo(()=>data?.payments.filter(p=>matchesPeriod(p,year,basis))??[],[data,year,basis]);
 const states=useMemo(()=>stateOptions(data?[...data.organizations.map(o=>o.state),...data.payments.map(p=>p.state)]:[]),[data]);
 const scope=useMemo(()=>period.filter(p=>(sector==="all"||p.sector===sector)&&matchesState(p.state,state)),[period,sector,state]);
 const amountFor=useCallback((p:Payment)=>p.amountCents??0,[]);
 const orgTotals=useMemo(()=>{const m=new Map<string,{total:number;count:number;review:number}>();for(const p of scope)for(const a of p.allocations){const v=m.get(a.organizationId)??{total:0,count:0,review:0};v.total+=a.amountCents;v.count++;if(!p.reviewed)v.review++;m.set(a.organizationId,v)}return m},[scope]);
 const orgs=useMemo(()=>data?.organizations.filter(o=>(sector==="all"||o.sector.includes(sector)||orgTotals.has(o.id))&&(matchesState(o.state,state)||orgTotals.has(o.id))&&[o.name,...o.aliases].join(" ").toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="state"?compareOrganizationStates(a,b):sort==="name"?a.name.localeCompare(b.name):(orgTotals.get(b.id)?.total??0)-(orgTotals.get(a.id)?.total??0)||a.name.localeCompare(b.name))??[],[data,sector,state,query,sort,orgTotals]);
 const active=orgs.find(o=>o.id===selected)??orgs[0];
 const orgPayments=scope.filter(p=>p.allocations.some(a=>a.organizationId===active?.id));
 const orgBenefits=data?.benefits.filter(b=>b.organizationIds.includes(active?.id??""))??[];
 const total=scope.reduce((s,p)=>s+amountFor(p),0),remaining=scope.reduce((s,p)=>s+(sector==="all"||p.sector===sector?unassigned(p):0),0);
 const expenseRows=scope.filter(p=>(filter!=="unassigned"||unassigned(p)>0)&&(filter!=="review"||!p.reviewed)&&[p.payee,p.description,...p.allocations.map(a=>orgMap.get(a.organizationId)?.name??"")].join(" ").toLowerCase().includes(expenseQuery.toLowerCase()));
 const saveExpense=async(p:Payment,body:unknown)=>{const result=await api("/api/expenses/"+p.id,"PUT",body);setData(d=>d?{...d,payments:d.payments.map(x=>x.id===p.id?result.payment:x)}:d);toast.success("Expense assignment saved");};
 useEffect(()=>{
   const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool||!data)return;
   const controller=new AbortController();
   for(const tool of [
    {name:"list_organization_spending",description:"Read organization totals in the currently selected market, state, and period.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>orgs.map(o=>({id:o.id,name:o.name,state:organizationStateLabel(o.state),amount:(orgTotals.get(o.id)?.total??0)/100,expenses:orgTotals.get(o.id)?.count??0}))},
    {name:"open_expense_assignment",description:"Open an expense for review. This only opens the editor; it does not save an assignment.",inputSchema:{type:"object",properties:{paymentId:{type:"string"}},required:["paymentId"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const id=(input as {paymentId?:string})?.paymentId;const p=data.payments.find(p=>p.id===id);if(!p)throw new Error("Expense not found");setEditing(p);return {paymentId:p.id,editorOpened:true,saved:false}}}
   ])try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}
   return()=>controller.abort();
 },[data,orgs,orgTotals]);
 const exportView=()=>downloadCsv("organization-spending-"+year+(state==="all"?"":"-"+state)+".csv",[["Organization","Sector","Organization state","Expense state filter","Period","Year basis","Assigned spending","Expenses"],...orgs.map(o=>[o.name,o.sector,organizationStateLabel(o.state),stateLabel(state),year,basis,(orgTotals.get(o.id)?.total??0)/100,orgTotals.get(o.id)?.count??0])]);
 return <div className="app-shell"><Toaster position="bottom-right" richColors/><header className="masthead"><CoreBrand/><div className="header-end"><Button variant="outline" onClick={exportView} disabled={!data}><Download size={16}/> Export totals</Button></div></header>
 <main><WorkspaceTools data={data} onReload={load}/><div className="page-heading"><div><p className="eyebrow">CORE MIDWEST / RELATIONSHIPS, DOLLARS & BENEFITS</p><h1>Client & organization spending.</h1></div><div className="global-filters"><label>Market<Choice label="Market" value={sector} onChange={setSector} options={[{value:"all",label:"All markets"},...Array.from(new Set(data?[...data.organizations.map(o=>o.sector),...data.payments.map(p=>p.sector)]:["K-12"])).sort().map(x=>({value:x,label:x}))]}/></label><label>State<Choice label="State" value={state} onChange={setState} options={states}/></label><label>Period<Choice label="Period" value={year} onChange={setYear} options={[{value:"all",label:"All years"},...[2027,2026,2025,2024,2023].map(x=>({value:String(x),label:String(x)})),{value:"unknown",label:"Year unknown"}]}/></label><label>Based on<Choice label="Year basis" value={basis} onChange={setBasis} options={[{value:"event",label:"Event / membership year"},{value:"approval",label:"Approval year"}]}/></label></div></div>
 {error&&<div role="alert" className="error-banner">{error}<Button variant="outline" onClick={load}><RefreshCw size={15}/>Retry</Button></div>}
 {!data?<div className="loading-state"><RefreshCw className="spin"/>Loading organization spending…</div>:<>
 {data.payments.length===0&&<div className="empty-workspace"><h2>Your shared workspace is ready.</h2><p>{canEdit()?"Use Import workspace above to load the private data file. Workspace owners can import; editors can review once it is loaded.":"Your workspace owner will import the organization and spending data."}</p></div>}
 <section className="metrics" aria-label="Spending summary"><div className="metric main-metric"><span>Recorded spending</span><strong>{money(total)}</strong><small>{scope.length} expenses · {year==="all"?"all years":year} · {sector==="all"?"all markets":sector} · {stateLabel(state)}</small></div><div className="metric"><span>Assigned to organizations</span><strong>{money(total-remaining)}</strong><small>{orgs.filter(o=>(orgTotals.get(o.id)?.count??0)>0).length} organizations with spending</small></div><button className="metric review-metric" onClick={()=>{setView("expenses");setFilter("unassigned");setExpenseQuery("")}}><span>Still to assign <ArrowUpRight size={17}/></span><strong>{money(remaining)}</strong><small>Review expenses without a full assignment</small></button></section>
 <div className="basis-note">Amounts come from the source tracker and your saved corrections. Payment settlement is not confirmed. Market follows the expense classification; you can change it when editing. State follows each expense’s recorded state. Organizations without spending use their listed states. Event year uses the first year stated in the description.</div>
 <Tabs value={view} onValueChange={setView} className="main-tabs"><div className="workspace-toolbar"><TabsList variant="line"><TabsTrigger value="organizations"><Building2/>Organizations</TabsTrigger><TabsTrigger value="expenses"><ReceiptText/>All expenses</TabsTrigger></TabsList><Button variant="ghost" disabled={!canEdit()} onClick={()=>setAdding(true)}><Plus size={16}/>Add organization</Button></div>
 <TabsContent value="organizations"><div className="organization-workspace"><aside className="organization-list"><div className="list-tools"><div className="search-field"><Search size={17}/><Input aria-label="Find an organization" placeholder="Find an organization…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="list-caption"><span>{orgs.length} organizations</span><Choice label="Organization sort" value={sort} onChange={setSort} options={[{value:"spend",label:"Highest spending"},{value:"name",label:"Name A–Z"},{value:"state",label:"State A–Z"}]}/></div></div><div className="org-scroll">{orgs.length===0?<div className="empty-state">No organizations match these filters.</div>:orgs.map(o=>{const s=orgTotals.get(o.id);return <button key={o.id} onClick={()=>setSelected(o.id)} className={"organization-item "+(active?.id===o.id?"selected":"")}><span className="org-item-heading"><OrganizationLogo organization={o}/><span><span className="org-item-name">{o.name}</span><span className="org-item-meta">{o.type||o.sector}{" · "+organizationStateLabel(o.state)}</span></span></span><span className="org-item-bottom"><strong>{money(s?.total??0)}</strong><span>{s?.count??0} expenses <ChevronRight size={14}/></span></span></button>})}</div></aside>
 <section className="organization-detail">{active?<><div className="org-hero"><div className="org-identity"><OrganizationLogo key={active.id} organization={active} size="large"/><div><p className="eyebrow">{active.sector} / {active.type||"ORGANIZATION"} / {organizationStateLabel(active.state)}</p><h2>{active.name}</h2><p className="subdued">{orgPayments.length} expenses · {orgBenefits.length} researched programs</p></div></div><div className="org-amount"><span>Assigned spending</span><strong>{money(orgTotals.get(active.id)?.total??0)}</strong><small>{year==="all"?"Across all years":year}</small></div></div>
 <LogoSource organization={active}/>{active.aliases.length>1&&<details className="included-names"><summary>Names grouped under this organization</summary><p>{active.aliases.join(" · ")}</p></details>}
 <Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="detail-tabs"><TabsTrigger value="spending">Spending breakdown</TabsTrigger><TabsTrigger value="benefits">Benefits & potential value <span className="count">{orgBenefits.length}</span></TabsTrigger></TabsList><TabsContent value="spending"><ExpenseTable payments={orgPayments} organizations={orgMap} activeId={active.id} onEdit={setEditing}/>{orgPayments.length>0&&<p className="table-note">Select an expense to change the organization, split the dollars, or add a correction.</p>}</TabsContent><TabsContent value="benefits"><div className="benefit-intro">Package terms below are from the tracker and organizer research. A published benefit does not confirm that it was purchased or used. Package prices are references, not additional spending.</div>{orgBenefits.length?orgBenefits.map(b=><BenefitCard key={b.id} benefit={b} onEdit={()=>setBenefitEdit(b)}/>):<div className="empty-state">No benefit package has been researched for this organization yet. Its assigned expenses remain available in the spending breakdown.</div>}</TabsContent></Tabs></>:<div className="empty-state">Choose an organization to review its spending and benefits.</div>}</section></div></TabsContent>
 <TabsContent value="expenses"><section className="expense-surface"><div className="expense-tools"><div className="search-field"><Search size={17}/><Input aria-label="Search expenses" placeholder="Search payee, description, or organization…" value={expenseQuery} onChange={e=>setExpenseQuery(e.target.value)}/></div><Choice label="Expense status" value={filter} onChange={setFilter} options={[{value:"all",label:"All expenses"},{value:"unassigned",label:"Still to assign"},{value:"review",label:"Not yet reviewed"}]}/><span>{expenseRows.length} expenses</span></div><ExpenseTable payments={expenseRows} organizations={orgMap} onEdit={setEditing}/></section></TabsContent></Tabs>
 <footer className="workspace-footer">CORE Midwest · Source: {data.meta.source||"Midwest BD & Marketing Tracker"} · Benefits researched {data.meta.researchAsOf||"September 21, 2026"} · {localPreview?"Local preview":"Shared edits refresh every 30 seconds"}</footer>
 </>}
 {data&&editing&&<ExpenseEditor payment={editing} organizations={data.organizations} onClose={()=>setEditing(null)} onSave={saveExpense} onReload={load}/>}
 {data&&<OrganizationEditor open={adding} onClose={()=>setAdding(false)} onCreated={o=>{setData(d=>d?{...d,organizations:[...d.organizations,o]}:d);setSelected(o.id);toast.success("Organization added")}}/>}
 {benefitEdit&&<BenefitEditor benefit={benefitEdit} onClose={()=>setBenefitEdit(null)} onSaved={b=>setData(d=>d?{...d,benefits:d.benefits.map(x=>x.id===b.id?b:x)}:d)}/>}
 </main></div>
}

function ExpenseTable({payments,organizations,activeId,onEdit}:{payments:Payment[];organizations:Map<string,Organization>;activeId?:string;onEdit:(p:Payment)=>void}){return !payments.length?<div className="empty-state"><ReceiptText size={27}/><h3>No spending in this period</h3><p>Try a different year or state, or review all expenses to assign spending here.</p></div>:<Table className="expense-table"><TableHeader><TableRow><TableHead>Expense / program</TableHead>{!activeId&&<TableHead>Assigned to</TableHead>}<TableHead className="text-right">{activeId?"Assigned amount":"Expense amount"}</TableHead><TableHead>Review</TableHead><TableHead><span className="sr-only">Edit</span></TableHead></TableRow></TableHeader><TableBody>{payments.map(p=><TableRow key={p.id}><TableCell><strong className="expense-description">{p.description||"Description not recorded"}</strong><span className="expense-meta">Paid to {p.payee||"Unknown payee"} · {p.approvalDate?.slice(0,10)||"Date unknown"} · {organizationStateLabel(p.state)}</span>{p.amountCents!==p.originalAmountCents&&<span className="corrected-label">Corrected from {money(p.originalAmountCents)}</span>}</TableCell>{!activeId&&<TableCell><span className="assignment-names">{p.allocations.map(a=>organizations.get(a.organizationId)?.name??"Unknown organization").join("; ")||"Unassigned"}</span>{unassigned(p)>0&&p.allocations.length>0&&<small>{money(unassigned(p))} still to assign</small>}</TableCell>}<TableCell className="amount-cell">{money(activeId?p.allocations.find(a=>a.organizationId===activeId)?.amountCents??0:p.amountCents)}{activeId&&p.allocations.length>1&&<small>of {money(p.amountCents)}</small>}</TableCell><TableCell><span className={"status "+(p.reviewed?"reviewed":"")}>{p.reviewed?<><Check size={12}/>Reviewed</>:p.confidence==="inferred"?"Suggested":"Not reviewed"}</span></TableCell><TableCell><Button variant="ghost" size="sm" aria-label={"Edit expense "+p.id} disabled={!canEdit()} onClick={()=>onEdit(p)}>Edit</Button></TableCell></TableRow>)}</TableBody></Table>}

function BenefitCard({benefit:b,onEdit}:{benefit:Benefit;onEdit:()=>void}){return <article className="benefit-card"><div className="benefit-header"><div><p className="eyebrow">{b.applicability.text}</p><h3>{b.program}</h3><p className="package-level">{b.trackedLevel}</p></div><Button variant="outline" size="sm" disabled={!canEdit()} onClick={onEdit}>Review benefit use</Button></div><div className="package-reference"><span>Recorded package / components</span><strong>{b.trackedPackageAmountText}</strong></div><div className="benefit-columns"><div><h4>What the package includes</h4><ul>{b.benefits.map((x,i)=><li key={i}>{x}</li>)}</ul></div><div className="value-box"><h4>Potential value</h4><p>{b.potentialValue}</p><span className="status">{b.utilization||"Not reviewed"}</span>{b.note&&<p className="saved-note">{b.note}</p>}</div></div><details><summary>Evidence, comparisons & sources</summary><p className="evidence-text">{b.evidence.status}</p>{b.alternatives.length>0&&<><h4>Other sponsorship levels</h4><ul>{b.alternatives.map((x,i)=><li key={i}>{x}</li>)}</ul></>}{b.openQuestions.length>0&&<><h4>To confirm</h4><ul>{b.openQuestions.map((x,i)=><li key={i}>{x}</li>)}</ul></>}<div className="source-links">{b.sources.map((url,i)=><a href={url} key={url} target="_blank" rel="noreferrer">Organizer source {i+1}<ExternalLink size={13}/></a>)}</div></details></article>}

function OrgPicker({organizations,value,onChange}:{organizations:Organization[];value:string;onChange:(id:string)=>void}){const options=[...organizations].sort((a,b)=>a.name.localeCompare(b.name));return <Combobox items={options} value={options.find(o=>o.id===value)??null} onValueChange={o=>onChange(o?.id??"")} itemToStringLabel={o=>o.name}><ComboboxInput aria-label="Assign to organization" placeholder="Find a client or organization…"/><ComboboxContent><ComboboxEmpty>No organization found</ComboboxEmpty><ComboboxList>{(o:Organization)=><ComboboxItem key={o.id} value={o}>{o.name}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox>}
function ExpenseEditor({payment:p,organizations,onClose,onSave,onReload}:{payment:Payment;organizations:Organization[];onClose:()=>void;onSave:(p:Payment,b:unknown)=>Promise<void>;onReload:()=>Promise<void>}){
 const [expenseSector,setExpenseSector]=useState(p.sector);
 const [amount,setAmount]=useState(p.amountCents===null?"":String(p.amountCents/100)),[allocations,setAllocations]=useState(p.allocations.map(a=>({organizationId:a.organizationId,amount:String(a.amountCents/100)}))),[note,setNote]=useState(p.note),[reviewed,setReviewed]=useState(p.reviewed),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const cents=amount===""?null:Math.round(Number(amount)*100),sum=allocations.reduce((s,a)=>s+Math.round(Number(a.amount)*100),0),balance=(cents??0)-sum;
 const save=async()=>{setBusy(true);setError("");try{if(amount!==""&&!/^\d+(\.\d{1,2})?$/.test(amount))throw new Error("Use dollars and up to two decimal places.");for(const a of allocations)if(!/^\d+(\.\d{1,2})?$/.test(a.amount))throw new Error("Enter valid dollars for each assignment.");await onSave(p,{sector:expenseSector,amountCents:cents,allocations:allocations.map(a=>({organizationId:a.organizationId,amountCents:Math.round(Number(a.amount)*100)})),note,reviewed,revision:p.revision});onClose();}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <Dialog open onOpenChange={o=>!o&&!busy&&onClose()}><DialogContent className="expense-dialog"><DialogHeader><DialogTitle>Assign this expense</DialogTitle><DialogDescription>{p.description}</DialogDescription></DialogHeader><div className="source-context"><span><strong>Paid to</strong>{p.payee}</span><span><strong>Source</strong>Payments, row {p.sourceRow}</span><span><strong>Original amount</strong>{money(p.originalAmountCents)}</span></div><label className="field-label">Market sector<Choice label="Expense market sector" value={expenseSector} onChange={setExpenseSector} options={Array.from(new Set([p.sector,...organizations.map(o=>o.sector)])).sort().map(x=>({value:x,label:x}))}/></label><label className="field-label">Expense amount ($)<Input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount unknown"/></label><p className="field-hint">Correct the amount if needed; the source value stays visible.</p><div className="allocation-heading"><h3>Spent for</h3><Button variant="ghost" size="sm" onClick={()=>setAllocations(a=>[...a,{organizationId:"",amount:balance>0?String(balance/100):""}])}><Plus size={15}/>Add / split assignment</Button></div>{allocations.length===0&&<div className="allocation-empty">No organization assigned. Add an assignment to include this expense in an organization’s total.</div>}{allocations.map((a,i)=><div className="allocation-row" key={i}><OrgPicker organizations={organizations} value={a.organizationId} onChange={id=>setAllocations(rows=>rows.map((r,j)=>j===i?{...r,organizationId:id}:r))}/><Input aria-label={"Assigned dollars "+(i+1)} inputMode="decimal" placeholder="$ Amount" value={a.amount} onChange={e=>setAllocations(rows=>rows.map((r,j)=>j===i?{...r,amount:e.target.value}:r))}/><Button variant="ghost" size="icon" aria-label="Remove assignment" onClick={()=>setAllocations(rows=>rows.filter((_,j)=>j!==i))}><X size={17}/></Button></div>)}<div className={"allocation-balance "+(balance<0?"overallocated":"")}><span>{balance<0?"Over-assigned":"Still to assign"}</span><strong>{money(Math.abs(balance))}</strong></div>{p.reason&&<p className="field-hint">Starting assignment: {p.reason}</p>}<label className="field-label">Review note<Textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Why this belongs to the client, what to confirm, or why the amount changed…"/></label><label className="checkbox-line"><Checkbox checked={reviewed} onCheckedChange={v=>setReviewed(v===true)}/>I have reviewed this expense and its assignment</label>{error&&<p className="form-error" role="alert">{error}{error.includes("changed")&&<button onClick={async()=>{await onReload();onClose()}}> Reload latest</button>}</p>}<DialogFooter><Button variant="outline" disabled={busy} onClick={onClose}>Cancel</Button><Button disabled={busy||balance<0} onClick={save}>{busy?"Saving…":"Save assignment"}</Button></DialogFooter></DialogContent></Dialog>
}
function OrganizationEditor({open,onClose,onCreated}:{open:boolean;onClose:()=>void;onCreated:(o:Organization)=>void}){const [name,setName]=useState(""),[sector,setSector]=useState("K-12"),[error,setError]=useState(""),[busy,setBusy]=useState(false);return <Dialog open={open} onOpenChange={o=>!o&&onClose()}><DialogContent><DialogHeader><DialogTitle>Add organization</DialogTitle><DialogDescription>Create a client or organization to assign spending to.</DialogDescription></DialogHeader><label className="field-label">Organization name<Input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field-label">Market sector<Input value={sector} onChange={e=>setSector(e.target.value)}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<DialogFooter><Button disabled={busy} onClick={async()=>{setBusy(true);try{const d=await api("/api/organizations","POST",{name,sector});onCreated(d.organization);setName("");setError("");onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?"Saving…":"Add organization"}</Button></DialogFooter></DialogContent></Dialog>}
function BenefitEditor({benefit:b,onClose,onSaved}:{benefit:Benefit;onClose:()=>void;onSaved:(b:Benefit)=>void}){const [note,setNote]=useState(b.note??""),[utilization,setUtilization]=useState(b.utilization??"Not reviewed"),[error,setError]=useState(""),[busy,setBusy]=useState(false);return <Dialog open onOpenChange={o=>!o&&!busy&&onClose()}><DialogContent><DialogHeader><DialogTitle>Review benefit use</DialogTitle><DialogDescription>{b.program} · {b.trackedLevel}</DialogDescription></DialogHeader><Choice label="Benefit use" value={utilization} onChange={setUtilization} options={["Not reviewed","Planned","Partly used","Fully used","Not used","Needs confirmation"].map(x=>({value:x,label:x}))}/><label className="field-label">What did we receive or use?<Textarea rows={5} value={note} onChange={e=>setNote(e.target.value)} placeholder="Registrations used, client meetings, advertising delivered, community impact…"/></label>{error&&<p role="alert" className="form-error">{error}</p>}<DialogFooter><Button variant="outline" onClick={onClose} disabled={busy}>Cancel</Button><Button disabled={busy} onClick={async()=>{setBusy(true);try{await api("/api/benefits/"+b.id,"PUT",{note,utilization,expectedNote:b.note||"",expectedUtilization:b.utilization||"Not reviewed"});onSaved({...b,note,utilization});toast.success("Benefit review saved");onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?"Saving…":"Save review"}</Button></DialogFooter></DialogContent></Dialog>}
