import assert from 'node:assert/strict';
import {applicableYear,matchesPeriod} from './review.ts';
const source={eventYear:2026,approvalYear:2025,approvalDate:'2025-11-15',amountCents:120000};
assert.equal(applicableYear(source),2026);
assert.equal(matchesPeriod(source,'2026','event'),true);
assert.equal(matchesPeriod(source,'2025','approval'),true);
const adjusted={...source,applicableYear:2027};
assert.equal(applicableYear(adjusted),2027);
assert.equal(matchesPeriod(adjusted,'2026','event'),false);
assert.equal(matchesPeriod(adjusted,'2027','event'),true);
assert.equal(matchesPeriod(adjusted,'2025','approval'),true);
assert.equal(adjusted.approvalDate,'2025-11-15');
assert.equal(adjusted.amountCents,120000);
assert.equal(adjusted.eventYear,2026);
assert.equal(matchesPeriod({...source,applicableYear:null},'unknown','event'),true);
assert.equal(matchesPeriod({...source,applicableYear:null},'2026','event'),false);
assert.equal(matchesPeriod(adjusted,'all','event'),true);
assert.equal(applicableYear({...source,applicableYear:undefined}),2026);
console.log('PASS 14 applicable-year checks: overrides, explicit unknown, approval-date separation, source preservation, and fallback.');
